version: '2'
networks:
  default:
    external:
      name: proxy
services:
  traefik:
    image: traefik:latest
    command: --web --docker --logLevel=DEBUG
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.priority: "100"
      traefik.frontend.rule: "Host:raspberrypi"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
