version: '3.7'
networks:
  default:
    name: proxy
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik
    restart: unless-stopped
    container_name: "traefik"
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --entrypoints.http.address=:80
      - --providers.docker=true
      - --api.insecure
    ports:
      # The HTTP port
      - "80:80"
      #- "8080:8080"
      # The Web UI (enabled by --api.insecure=true)
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=hostregexp(`traefik.{domain:.+}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"