version: "3"
networks:
  default:
    external:
      name: proxy
services:
  project1:
    image: tobi312/rpi-nginx
    container_name: project1
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.priority: "10"
      traefik.frontend.rule: "HostRegexp:{subdomain:[a-z]+}.level14.de"
    environment:
      - http_proxy
      - https_proxy
      - ftp_proxy
      - no_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ${PWD}:/app

