version: "3"
networks:
  default:
    external:
      name: proxy
services:
  project:
    image: tobi312/rpi-nginx
    container_name: project2
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.priority: "10"
      traefik.frontend.rule: "Host: 192.168.178.52"
    environment:
      - http_proxy
      - https_proxy
      - ftp_proxy
      - no_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ${PWD}:/app
  php:
    image: shaula/rpi-php7-fpm:7.1
    container_name: php2
    restart: unless-stopped
    volumes:
      - ${PWD}:/app
  postgres:
    image: tobi312/rpi-postgresql
    container_name: postgres
    restart: unless-stopped
