version: "3"
networks:
  default:
    external:
      name: proxy
services:
  project:
    image: emnili/rpi-nginx
    container_name: project2
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.priority: "10"
      traefik.frontend.rule: "Host: 192.168.178.58"
    environment:
      - http_proxy
      - https_proxy
      - ftp_proxy
      - no_proxy
    volumes:
      - ./nginx.conf:/app/nginx.conf
      - ${PWD}/app:/app
  php:
    image: emnili/rpi-php
    container_name: php
    restart: unless-stopped
    volumes:
      - ${PWD}/app:/app
  postgres:
    image: emnili/rpi-postgres
    container_name: postgres
    restart: unless-stopped
