version: "3.7"
networks:
  default:
    external:
      name: proxy
  intern: {}
volumes:
    app: {}
    db: {}
    tmp: {}
    file: {} 
services:
  postgres:
    image: emnili/rpi-postgres
    container_name: postgres
    restart: unless-stopped
    networks:
        default: {}
        intern:
            aliases:
                - db
    volumes:
      - source: db
        target: /data
        type: volume
      - source: file
        target: /app
        type: volume
  php:
    image: emnili/rpi-php
    container_name: php
    restart: unless-stopped
    networks:
        default: {}
        intern:
            aliases:
                - php
    volumes:
            - source: ${PWD}/cms
              target: /app
              type: bind
            - source: file
              target: /data/file
              type: volume
            - source: tmp
              target: /tmp
              type: volume
  project:
    image: emnili/rpi-nginx
    container_name: project2
    restart: unless-stopped
    networks:
        default: {}
        intern:
            aliases:
                - www
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.priority: "10"
      traefik.frontend.rule: "Host: 192.168.178.58"
      traefik.docker.network: "proxy"
    environment:
      - http_proxy
      - https_proxy
      - ftp_proxy
      - no_proxy
    volumes:
      - ./nginx.conf:/app/nginx.conf
      - source: ${PWD}/cms
        target: /app
        type: bind
      - source: file
        target: /data/file
        type: volume
