version: "3"
networks:
  default:
    external:
      name: proxy
volumes:
 gogs: {}
services:
 gogs:
  container_name: gogs
  restart: unless-stopped
  image: hypriot/rpi-gogs-raspbian
  volumes:
    - gogs:/gogs-data
  labels:
    traefik.enable: "true"
    traefik.port: "3000"
    traefik.frontend.rule: "Host:buffy.level14.de"
    traefik.frontend.priority: "120"
